"""empty message

Revision ID: cb96c2e9011a
Revises: c846089f2d79
Create Date: 2026-05-29 11:32:27.148731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb96c2e9011a'
down_revision = 'c846089f2d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_group_owner", 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint("fk_group_owner", type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
